const cfg=window.ZAP_TMS_CONFIG;
const sb=window.supabase.createClient(cfg.url,cfg.token);
const $=id=>document.getElementById(id);
const store={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let currentUser=null;
let appData={settings:store.get("settings",{companyName:"Zap Dispatch",defaultCommission:8,companyEmail:"",companyPhone:""}),carriers:[],brokers:[],loads:[],expenses:[]};
const tables=["carriers","brokers","loads","expenses"];
const map={carriers:{toDb:x=>({name:x.name||"",mc_dot:x.mcDot||"",contact:x.contact||"",phone:x.phone||"",email:x.email||"",equipment:x.equipment||"",trucks:num(x.trucks,0),commission:num(x.commission,8),user_id:currentUser.id}),fromDb:x=>({id:x.id,name:x.name,mcDot:x.mc_dot,contact:x.contact,phone:x.phone,email:x.email,equipment:x.equipment,trucks:x.trucks,commission:x.commission})},brokers:{toDb:x=>({name:x.name||"",contact:x.contact||"",phone:x.phone||"",email:x.email||"",source:x.source||"",notes:x.notes||"",user_id:currentUser.id}),fromDb:x=>({id:x.id,name:x.name,contact:x.contact,phone:x.phone,email:x.email,source:x.source,notes:x.notes})},loads:{toDb:x=>({carrier:x.carrier||"",broker:x.broker||"",pickup:x.pickup||"",delivery:x.delivery||"",pickup_date:emptyDate(x.pickupDate),delivery_date:emptyDate(x.deliveryDate),equipment:x.equipment||"",status:x.status||"Booked",rate:num(x.rate,0),commission_pct:num(x.commissionPct,8),load_number:x.loadNumber||"",notes:x.notes||"",user_id:currentUser.id}),fromDb:x=>({id:x.id,carrier:x.carrier,broker:x.broker,pickup:x.pickup,delivery:x.delivery,pickupDate:x.pickup_date,deliveryDate:x.delivery_date,equipment:x.equipment,status:x.status,rate:x.rate,commissionPct:x.commission_pct,loadNumber:x.load_number,notes:x.notes})},expenses:{toDb:x=>({carrier:x.carrier||"",category:x.category||"Other",amount:num(x.amount,0),expense_date:emptyDate(x.date),notes:x.notes||"",user_id:currentUser.id}),fromDb:x=>({id:x.id,carrier:x.carrier,category:x.category,amount:x.amount,date:x.expense_date,notes:x.notes})}};
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}function emptyDate(v){return v||null}function money(n){return "$"+(Number(n)||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}function msg(t,bad=false){const el=$("authMessage");if(el){el.textContent=t||"";el.classList.toggle("bad",!!bad)}}function setBusy(b){["loginBtn","signupBtn","addCarrier","addBroker","addLoad","addExpense","syncNow"].forEach(id=>{const el=$(id);if(el)el.disabled=b})}
function data(){return appData}function cache(){tables.forEach(t=>store.set(t,appData[t]));store.set("settings",appData.settings)}
async function loadCloud(){if(!currentUser)return;setBusy(true);try{for(const t of tables){const {data,error}=await sb.from(t).select("*").order("created_at",{ascending:false});if(error)throw error;appData[t]=(data||[]).map(map[t].fromDb)}cache();refresh()}catch(e){alert("Cloud sync error: "+e.message)}finally{setBusy(false)}}
async function insertRow(t,row){setBusy(true);try{const {data,error}=await sb.from(t).insert(map[t].toDb(row)).select().single();if(error)throw error;appData[t]=[map[t].fromDb(data),...appData[t]];cache();refresh()}catch(e){alert("Save error: "+e.message)}finally{setBusy(false)}}
async function updateRow(t,item){if(!item.id)return;setBusy(true);try{const {data,error}=await sb.from(t).update(map[t].toDb(item)).eq("id",item.id).select().single();if(error)throw error;const idx=appData[t].findIndex(x=>x.id===item.id);if(idx>-1)appData[t][idx]=map[t].fromDb(data);cache();refresh()}catch(e){alert("Update error: "+e.message)}finally{setBusy(false)}}
async function removeItem(t,i){const item=appData[t][i];if(!item)return;if(!confirm("Delete this item?"))return;setBusy(true);try{if(item.id){const {error}=await sb.from(t).delete().eq("id",item.id);if(error)throw error}appData[t].splice(i,1);cache();refresh()}catch(e){alert("Delete error: "+e.message)}finally{setBusy(false)}}window.removeItem=removeItem;
function refresh(){renderSelects();renderDashboard();renderCarriers();renderBrokers();renderLoads();renderExpenses();renderInvoices();renderSettings()}
function renderDashboard(){const d=data();const gross=d.loads.reduce((s,l)=>s+num(l.rate),0);const comm=d.loads.reduce((s,l)=>s+(num(l.rate)*num(l.commissionPct)/100),0);$("dashRevenue").textContent=money(gross);$("dashCommission").textContent=money(comm);$("carrierCount").textContent=d.carriers.length;$("truckCount").textContent=d.carriers.reduce((s,c)=>s+num(c.trucks),0);$("loadCount").textContent=d.loads.length;$("openLoads").textContent=d.loads.filter(l=>!["Paid","Cancelled"].includes(l.status)).length}
function renderSelects(){const d=data();["loadCarrier","expenseCarrier"].forEach(id=>{const sel=$(id);if(!sel)return;const old=sel.value;sel.innerHTML="<option value=''>Select</option>";d.carriers.forEach(c=>{let o=document.createElement("option");o.value=c.name;o.textContent=c.name;sel.appendChild(o)});sel.value=old});const bsel=$("loadBroker");if(bsel){const old=bsel.value;bsel.innerHTML="<option value=''>Select</option>";d.brokers.forEach(b=>{let o=document.createElement("option");o.value=b.name;o.textContent=b.name;bsel.appendChild(o)});bsel.value=old}}
function esc(v){return String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[m]))}function card(title,body,pills="",actions=""){return `<div class="list-card"><h3>${esc(title)}</h3><p class="muted">${esc(body)}</p><div class="pill-row">${pills}</div>${actions}</div>`}
function renderCarriers(){const list=$("carriersList"),arr=data().carriers;list.innerHTML=arr.length?"":"<div class='card'><p class='muted'>No carriers yet.</p></div>";arr.forEach((c,i)=>list.innerHTML+=card(c.name||"Unnamed carrier",`${c.equipment||""} • ${c.trucks||0} truck(s) • ${c.contact||""} ${c.phone||""}`,`<span class="pill">MC/DOT: ${esc(c.mcDot||"-")}</span><span class="pill green">${esc(c.commission||8)}%</span>`,`<div class="card-actions"><button class="small-btn" onclick="removeItem('carriers',${i})">Delete</button></div>`))}
function renderBrokers(){const list=$("brokersList"),arr=data().brokers;list.innerHTML=arr.length?"":"<div class='card'><p class='muted'>No brokers yet.</p></div>";arr.forEach((b,i)=>list.innerHTML+=card(b.name||"Unnamed broker",`${b.contact||""} • ${b.phone||""} • ${b.email||""}`,`<span class="pill">${esc(b.source||"Source")}</span>`,`<div class="card-actions"><button class="small-btn" onclick="removeItem('brokers',${i})">Delete</button></div>`))}
function renderLoads(){const list=$("loadsList"),arr=data().loads;list.innerHTML=arr.length?"":"<div class='card'><p class='muted'>No loads yet.</p></div>";arr.forEach((l,i)=>{const color=l.status==="Paid"?"green":l.status==="Cancelled"?"red":l.status==="Delivered"||l.status==="Invoiced"?"yellow":"orange";const comm=num(l.rate)*num(l.commissionPct)/100;list.innerHTML+=card(`${l.pickup||"Pickup"} → ${l.delivery||"Delivery"}`,`${l.carrier||"Carrier"} • ${l.broker||"Broker"} • Load # ${l.loadNumber||"-"} • ${l.pickupDate||""}`,`<span class="pill ${color}">${esc(l.status||"Booked")}</span><span class="pill">${money(l.rate)}</span><span class="pill green">Comm ${money(comm)}</span><span class="pill">${esc(l.equipment||"")}</span>`,`<div class="card-actions"><button class="small-btn" onclick="cycleLoad(${i})">Next status</button><button class="small-btn" onclick="removeItem('loads',${i})">Delete</button></div>`)})}
async function cycleLoad(i){const statuses=["Booked","Dispatched","Picked Up","Delivered","Invoiced","Paid"];const l=appData.loads[i];if(!l)return;let idx=statuses.indexOf(l.status);l.status=statuses[(idx+1)%statuses.length];await updateRow("loads",l)}window.cycleLoad=cycleLoad;
function renderExpenses(){const list=$("expensesList"),arr=data().expenses;list.innerHTML=arr.length?"":"<div class='card'><p class='muted'>No expenses yet.</p></div>";arr.forEach((e,i)=>list.innerHTML+=card(`${e.category||"Other"} • ${money(e.amount)}`,`${e.date||""} • ${e.carrier||""} • ${e.notes||""}`,`<span class="pill red">Cost</span>`,`<div class="card-actions"><button class="small-btn" onclick="removeItem('expenses',${i})">Delete</button></div>`))}
function renderInvoices(){const list=$("invoiceList"),arr=data().loads.filter(l=>["Delivered","Invoiced","Paid"].includes(l.status));list.innerHTML=arr.length?"":"<div class='card'><p class='muted'>No delivered/invoiced loads yet.</p></div>";arr.forEach(l=>{const comm=num(l.rate)*num(l.commissionPct)/100;list.innerHTML+=card(`${l.carrier||"Carrier"} • ${money(l.rate)}`,`${l.pickup||""} → ${l.delivery||""} • Broker: ${l.broker||""}`,`<span class="pill">${esc(l.status)}</span><span class="pill green">Dispatch fee ${money(comm)}</span>`)})}
function renderSettings(){const s=data().settings;$("companyName").value=s.companyName||"";$("defaultCommission").value=s.defaultCommission||8;$("companyEmail").value=s.companyEmail||"";$("companyPhone").value=s.companyPhone||""}
function clearInputs(ids){ids.forEach(id=>{const el=$(id);if(el)el.value=""})}function navTo(target){document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.screen===target));document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===target))}
document.querySelectorAll(".nav-btn,.jump").forEach(btn=>btn.onclick=()=>{if(btn.dataset.screen)navTo(btn.dataset.screen)});
$("themeToggle").onclick=()=>{document.body.classList.toggle("light");store.set("light",document.body.classList.contains("light"))};
$("addCarrier").onclick=()=>insertRow("carriers",{name:$("carrierName").value,mcDot:$("mcDot").value,contact:$("carrierContact").value,phone:$("carrierPhone").value,email:$("carrierEmail").value,equipment:$("carrierEquipment").value,trucks:$("carrierTrucks").value,commission:$("carrierCommission").value}).then(()=>clearInputs(["carrierName","mcDot","carrierContact","carrierPhone","carrierEmail"]));
$("addBroker").onclick=()=>insertRow("brokers",{name:$("brokerName").value,contact:$("brokerContact").value,phone:$("brokerPhone").value,email:$("brokerEmail").value,source:$("brokerSource").value,notes:$("brokerNotes").value}).then(()=>clearInputs(["brokerName","brokerContact","brokerPhone","brokerEmail","brokerSource","brokerNotes"]));
$("addLoad").onclick=()=>insertRow("loads",{carrier:$("loadCarrier").value,broker:$("loadBroker").value,pickup:$("pickup").value,delivery:$("delivery").value,pickupDate:$("pickupDate").value,deliveryDate:$("deliveryDate").value,equipment:$("equipment").value,status:$("loadStatus").value,rate:$("rate").value,commissionPct:$("commissionPct").value,loadNumber:$("loadNumber").value,notes:$("loadNotes").value}).then(()=>clearInputs(["pickup","delivery","pickupDate","deliveryDate","rate","loadNumber","loadNotes"]));
$("addExpense").onclick=()=>insertRow("expenses",{date:$("expenseDate").value,carrier:$("expenseCarrier").value,category:$("expenseCategory").value,amount:$("expenseAmount").value,notes:$("expenseNotes").value}).then(()=>clearInputs(["expenseAmount","expenseNotes"]));
$("saveSettings").onclick=()=>{appData.settings={companyName:$("companyName").value,defaultCommission:$("defaultCommission").value,companyEmail:$("companyEmail").value,companyPhone:$("companyPhone").value};cache();alert("Settings saved on this device.");refresh()};
$("exportData").onclick=()=>{$("backupBox").value=JSON.stringify(data(),null,2)};$("syncNow").onclick=loadCloud;$("logoutBtn").onclick=async()=>{await sb.auth.signOut();location.reload()};
async function sendLink(){const email=$("authEmail").value.trim();if(!email)return msg("Enter your email first.",true);setBusy(true);msg("Sending login link...");const res=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});setBusy(false);if(res.error)return msg(res.error.message,true);msg("Check your email and open the login link on this device.")}
$("loginBtn").onclick=sendLink;$("signupBtn").onclick=sendLink;$("showLogin").onclick=()=>msg("");$("showSignup").onclick=()=>msg("Enter your email and press Create user to receive a login link.");
async function migrateLocal(){const done=store.get("tmsMigratedToCloud",false);if(done||!currentUser)return;let moved=0;for(const t of tables){const old=store.get(t,[]).filter(x=>!x.id);for(const row of old){const {error}=await sb.from(t).insert(map[t].toDb(row));if(!error)moved++}}store.set("tmsMigratedToCloud",true);if(moved)alert(`Imported ${moved} old local records to cloud.`)}
async function startApp(){const {data:{session}}=await sb.auth.getSession();currentUser=session?.user;if(!currentUser){$("authShell").classList.remove("hidden");$("appShell").classList.add("hidden");return}$("authShell").classList.add("hidden");$("appShell").classList.remove("hidden");$("userEmail").textContent=currentUser.email||"";await migrateLocal();await loadCloud()}
if(store.get("light",false))document.body.classList.add("light");startApp();if("serviceWorker"in navigator){navigator.serviceWorker.register("service-worker.js").catch(()=>{})}