(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const loads=()=>{try{return JSON.parse(localStorage.getItem('loads')||'[]')}catch{return[]}};
const ok=s=>['delivered','invoiced','paid'].includes(String(s||'').toLowerCase());
const esc=s=>String(s??'').replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]));
const money=n=>'$'+Number(n||0).toFixed(2);
function addTop(){if(q('#invoiceSelectedBtn'))return;const bar=q('#folderBar')||q('#loads .section-title');if(!bar)return;const b=document.createElement('button');b.id='invoiceSelectedBtn';b.className='primary-btn';b.textContent='Invoice selected';b.style.marginTop='10px';b.onclick=invoiceSelected;bar.appendChild(b)}
function markCards(){const arr=loads();qa('#loadsList .list-card').forEach((card,i)=>{const l=arr[i];if(!l||!ok(l.status))return;let box=card.querySelector('.invoice-select-box');if(!box){box=document.createElement('label');box.className='invoice-select-box';box.style.cssText='display:flex;gap:8px;align-items:center;margin-top:8px;font-weight:800;color:#86efac';box.innerHTML='<input type="checkbox" class="invoice-select"> Select for invoice';card.prepend(box)}box.querySelector('input').dataset.id=l.id})}
async function invoiceSelected(){const ids=qa('.invoice-select:checked').map(x=>x.dataset.id).filter(Boolean);if(!ids.length)return alert('Select at least one load.');const r=await sb.from('loads').select('*').in('id',ids).order('delivery_date',{ascending:true});if(r.error)return alert(r.error.message);const items=r.data||[];if(!items.length)return alert('No loads found.');const carriers=[...new Set(items.map(x=>x.carrier||''))];if(carriers.length>1)return alert('Select loads from only one carrier.');let total=0;const rows=items.map(x=>{const rate=Number(x.rate||0),pct=Number(x.commission_pct||0),due=rate*pct/100;total+=due;return '<tr><td>'+esc(x.load_number||'-')+'</td><td>'+esc((x.pickup||'')+' → '+(x.delivery||''))+'</td><td>'+esc(x.delivery_date||x.pickup_date||'')+'</td><td>'+money(rate)+'</td><td>'+pct+'%</td><td>'+money(due)+'</td></tr>'}).join('');const carrier=carriers[0]||'Carrier';const html='<!doctype html><html><head><title>Invoice - '+esc(carrier)+'</title><style>body{font-family:Arial,sans-serif;color:#111;padding:30px}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:22px}td,th{border:1px solid #ccc;padding:9px;font-size:13px;text-align:left}th{background:#f2f2f2}.top{display:flex;justify-content:space-between;gap:20px}.total{text-align:right;font-size:22px;font-weight:800;margin-top:18px}.pay{margin-top:28px;padding:14px;border:1px solid #ddd;background:#fafafa}.btn{margin:18px 0;padding:10px 14px;border:0;background:#0f766e;color:white;border-radius:8px}@media print{.btn{display:none}}</style></head><body><button class="btn" onclick="window.print()">Print / Save as PDF</button><div class="top"><div><h1>ZAP DISPATCH</h1><p>Carrier Invoice</p></div><div><b>Invoice Date:</b> '+new Date().toLocaleDateString()+'<br><b>Carrier:</b> '+esc(carrier)+'</div></div><table><thead><tr><th>Load #</th><th>Lane</th><th>Date</th><th>Rate</th><th>Dispatch %</th><th>Amount Due</th></tr></thead><tbody>'+rows+'</tbody></table><div class="total">Total Due: '+money(total)+'</div><div class="pay"><b>Payment:</b><br>Zelle payment details can be added here.<br>For card/ACH payments, Stripe or Square checkout can be integrated later.</div></body></html>';const w=window.open('','_blank');if(!w)return alert('Popup blocked. Allow popups for this site.');w.document.write(html);w.document.close();setTimeout(()=>w.print(),700)}
setInterval(()=>{addTop();markCards()},1500);
})();