(()=>{
const get=()=>{try{return JSON.parse(localStorage.getItem('loads')||'[]')}catch{return[]}};
async function go(i){const l=get()[i];if(!l||!l.id)return alert('Sync first.');const r=await sb.rpc('create_driver_link',{p_load_id:l.id});if(r.error)return alert(r.error.message);const base=location.origin+location.pathname.replace(/index\.html$/,'').replace(/\/$/,'/');const url=base+'portal.html?t='+r.data;try{await navigator.clipboard.writeText(url);alert('Copied:\n'+url)}catch{prompt('Copy:',url)}}
async function docs(i){const l=get()[i];if(!l||!l.id)return alert('Sync first.');const r=await sb.from('load_documents').select('file_name,file_type,file_data,created_at').eq('load_id',l.id).order('created_at',{ascending:false});if(r.error)return alert(r.error.message);if(!r.data||!r.data.length)return alert('No documents saved for this load yet.');const w=window.open('','_blank');w.document.write('<h2>Load Documents</h2>');r.data.forEach(d=>{w.document.write('<p><b>'+d.file_name+'</b><br>'+new Date(d.created_at).toLocaleString()+'</p><p><a href="'+d.file_data+'" target="_blank" download="'+d.file_name+'">Open / Download</a></p><hr>')});w.document.close()}
async function loc(i){const l=get()[i];if(!l||!l.id)return alert('Sync first.');const r=await sb.from('load_events').select('latitude,longitude,created_at,event_type').eq('load_id',l.id).not('latitude','is',null).not('longitude','is',null).order('created_at',{ascending:false}).limit(1);if(r.error)return alert(r.error.message);if(!r.data||!r.data.length)return alert('No location received yet.');const x=r.data[0];window.open('https://www.google.com/maps?q='+x.latitude+','+x.longitude,'_blank')}
function add(){document.querySelectorAll('#loadsList .list-card').forEach((c,i)=>{if(c.querySelector('.load-link-btn'))return;let a=c.querySelector('.card-actions');if(!a){a=document.createElement('div');a.className='card-actions';c.appendChild(a)}let b=document.createElement('button');b.className='small-btn load-link-btn';b.textContent='Driver Link';b.onclick=()=>go(i);let d=document.createElement('button');d.className='small-btn load-docs-btn';d.textContent='Docs';d.onclick=()=>docs(i);let p=document.createElement('button');p.className='small-btn load-loc-btn';p.textContent='Location';p.onclick=()=>loc(i);a.insertBefore(p,a.firstChild);a.insertBefore(d,a.firstChild);a.insertBefore(b,a.firstChild)})}
function helpers(){if(!document.getElementById('phase2Helper')){const s=document.createElement('script');s.id='phase2Helper';s.src='phase2.js?v=2';document.body.appendChild(s)}if(!document.getElementById('invoiceSelectHelper')){const h=document.createElement('script');h.id='invoiceSelectHelper';h.src='invoice-select.js?v=1';document.body.appendChild(h)}}
setInterval(add,1000);
setTimeout(helpers,1000);
})();