(()=>{
const by=id=>document.getElementById(id);
const loads=()=>{try{return JSON.parse(localStorage.getItem('loads')||'[]')}catch{return[]}};
let editId=null,busy=false,lastShow=0,folder=localStorage.getItem('zapFolder')||'active';
function input(after,id,label,type='text',ph=''){if(by(id))return;const a=by(after);if(!a)return;const l=document.createElement('label');l.textContent=label;const x=document.createElement('input');x.id=id;x.type=type;x.placeholder=ph;l.appendChild(x);a.closest('label')?.after(l)}
function area(after,id,label,ph=''){if(by(id))return;const a=by(after);if(!a)return;const l=document.createElement('label');l.textContent=label;const x=document.createElement('textarea');x.id=id;x.rows=3;x.placeholder=ph;l.appendChild(x);a.closest('label')?.after(l)}
function full(addr,city){addr=(addr||'').trim();city=(city||'').trim();if(!addr)return '';if(city&&addr.toLowerCase().indexOf(city.toLowerCase())<0)return addr+', '+city;return addr}
function setv(id,v){const e=by(id);if(e)e.value=v??''}
function grp(s){s=(s||'').toLowerCase();if(s==='paid')return'paid';if(['delivered','invoiced','cancelled'].includes(s))return'completed';return'active'}
function fields(){input('pickup','pickupAddress','Full pickup address','text','Street address only');input('delivery','deliveryAddress','Full delivery address','text','Street address only');input('deliveryAddress','loadMiles','Miles','number','Loaded miles');area('loadMiles','extraStops','Multiple stops / extra stops','Stop 1 Pickup - full address - appt\nStop 2 Delivery - full address - appt');editButtons();folderBar()}
function row(){const pu=by('pickup')?.value||'',de=by('delivery')?.value||'';return {carrier:by('loadCarrier').value||'',broker:by('loadBroker').value||'',pickup:pu,delivery:de,pickup_address:full(by('pickupAddress')?.value,pu),delivery_address:full(by('deliveryAddress')?.value,de),miles:Number(by('loadMiles')?.value||0),additional_stops:by('extraStops')?.value||'',pickup_date:by('pickupDate').value||null,delivery_date:by('deliveryDate').value||null,pickup_time:by('pickupTime')?.value||'',delivery_time:by('deliveryTime')?.value||'',driver_name:by('driverName')?.value||'',driver_phone:by('driverPhone')?.value||'',truck_number:by('truckNumber')?.value||'',trailer_number:by('trailerNumber')?.value||'',equipment:by('equipment').value||'',status:by('loadStatus').value||'Booked',rate:Number(by('rate').value||0),commission_pct:Number(by('commissionPct').value||8),load_number:by('loadNumber').value||'',notes:by('loadNotes').value||''}}
function clear(){['pickup','delivery','pickupAddress','deliveryAddress','loadMiles','extraStops','pickupDate','deliveryDate','pickupTime','deliveryTime','driverName','driverPhone','truckNumber','trailerNumber','rate','loadNumber','loadNotes'].forEach(id=>{const e=by(id);if(e)e.value=''});editId=null;busy=false;const a=by('applyEditLoad');if(a)a.style.display='none';const c=by('cancelEditLoad');if(c)c.style.display='none';const s=by('editModeNotice');if(s)s.textContent=''}
async function newSave(){const u=(await sb.auth.getSession()).data.session?.user;if(!u)return alert('Login again first.');const x=await sb.from('loads').insert({...row(),user_id:u.id});if(x.error)return alert('Save error: '+x.error.message);clear();if(typeof loadCloud==='function')await loadCloud()}
async function applyEdit(){if(!editId||busy)return;busy=true;const x=await sb.from('loads').update(row()).eq('id',editId);busy=false;if(x.error)return alert('Update error: '+x.error.message);alert('Load updated.');clear();if(typeof loadCloud==='function')await loadCloud()}
function hook(){const b=by('addLoad');if(b&&!b.dataset.phase2save){b.dataset.phase2save='1';b.onclick=newSave}}
function editButtons(){const b=by('addLoad');if(!b)return;if(!by('applyEditLoad')){const a=document.createElement('button');a.id='applyEditLoad';a.className='primary-btn';a.textContent='Apply edit';a.style.display='none';a.onclick=applyEdit;b.after(a)}if(!by('cancelEditLoad')){const c=document.createElement('button');c.id='cancelEditLoad';c.className='small-btn';c.textContent='Cancel edit';c.style.display='none';c.onclick=clear;by('applyEditLoad').after(c)}if(!by('editModeNotice')){const n=document.createElement('p');n.id='editModeNotice';n.className='muted';n.style.fontWeight='800';n.style.color='#86efac';b.closest('.section-title')?.after(n)}}
function folderBar(){if(by('folderBar'))return;const t=document.querySelector('#loads .section-title');if(!t)return;const d=document.createElement('div');d.id='folderBar';d.className='card';d.style.padding='12px';d.style.margin='0 0 12px';d.innerHTML='<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px"><button class="small-btn fb" data-f="active">Active</button><button class="small-btn fb" data-f="completed">Completed</button><button class="small-btn fb" data-f="paid">Paid</button></div><p id="folderNote" class="muted" style="margin:8px 0 0"></p>';t.after(d);d.querySelectorAll('.fb').forEach(b=>b.onclick=()=>{folder=b.dataset.f;localStorage.setItem('zapFolder',folder);filterCards()})}
async function editById(id){if(busy)return;busy=true;const r=await sb.from('loads').select('*').eq('id',id).single();busy=false;if(r.error)return alert(r.error.message);const x=r.data;editId=x.id;fields();setv('loadCarrier',x.carrier);setv('loadBroker',x.broker);setv('pickup',x.pickup);setv('delivery',x.delivery);setv('pickupAddress',x.pickup_address);setv('deliveryAddress',x.delivery_address);setv('loadMiles',x.miles);setv('extraStops',x.additional_stops);setv('pickupDate',x.pickup_date);setv('deliveryDate',x.delivery_date);setv('pickupTime',x.pickup_time);setv('deliveryTime',x.delivery_time);setv('driverName',x.driver_name);setv('driverPhone',x.driver_phone);setv('truckNumber',x.truck_number);setv('trailerNumber',x.trailer_number);setv('equipment',x.equipment);setv('loadStatus',x.status);setv('rate',x.rate);setv('commissionPct',x.commission_pct);setv('loadNumber',x.load_number);setv('loadNotes',x.notes);const a=by('applyEditLoad');if(a)a.style.display='block';const c=by('cancelEditLoad');if(c)c.style.display='inline-block';const n=by('editModeNotice');if(n)n.textContent='Editing load # '+(x.load_number||x.id)+'. Use Apply edit to save changes.';by('loads')?.scrollIntoView({behavior:'smooth',block:'start'})}
function filterCards(){const a=loads(),cnt={active:0,completed:0,paid:0};a.forEach(x=>cnt[grp(x.status)]++);document.querySelectorAll('.fb').forEach(b=>{const f=b.dataset.f;b.classList.toggle('active-tab',f===folder);b.textContent=(f==='active'?'Active':f==='completed'?'Completed':'Paid')+' ('+(cnt[f]||0)+')'});const n=by('folderNote');if(n)n.textContent=folder==='active'?'Active Loads':folder==='completed'?'Completed Loads':'Paid Archive';document.querySelectorAll('#loadsList .list-card').forEach((card,i)=>{const l=a[i];if(l)card.style.display=grp(l.status)===folder?'block':'none'})}
async function show(){if(editId)return;const now=Date.now();if(now-lastShow<5000){filterCards();return}lastShow=now;const a=loads(),ids=a.map(x=>x.id).filter(Boolean);if(!ids.length)return;const r=await sb.from('loads').select('id,miles,pickup_address,delivery_address,additional_stops').in('id',ids);if(r.error||!r.data)return;const m=Object.fromEntries(r.data.map(x=>[x.id,x]));document.querySelectorAll('#loadsList .list-card').forEach((card,i)=>{const l=a[i];if(!l||!l.id)return;let acts=card.querySelector('.card-actions');if(!acts){acts=document.createElement('div');acts.className='card-actions';card.appendChild(acts)}let e=card.querySelector('.edit-load-btn');if(!e){e=document.createElement('button');e.className='small-btn edit-load-btn';e.textContent='Edit';acts.appendChild(e)}e.onclick=()=>editById(l.id);const x=m[l.id]||{};let p=card.querySelector('.phase2-line');if(!p){p=document.createElement('p');p.className='muted phase2-line';card.appendChild(p)}p.textContent='Miles: '+(x.miles||'-')+' | PU address: '+(x.pickup_address||'-')+' | DEL address: '+(x.delivery_address||'-')});filterCards()}
setInterval(()=>{fields();hook();show()},1500);
})();