(()=>{
const by=id=>document.getElementById(id);
const loads=()=>{try{return JSON.parse(localStorage.getItem('loads')||'[]')}catch{return[]}};
let editId=null;
function input(after,id,label,type='text',ph=''){if(by(id))return;const a=by(after);if(!a)return;const l=document.createElement('label');l.textContent=label;const x=document.createElement('input');x.id=id;x.type=type;x.placeholder=ph;l.appendChild(x);a.closest('label')?.after(l)}
function area(after,id,label,ph=''){if(by(id))return;const a=by(after);if(!a)return;const l=document.createElement('label');l.textContent=label;const x=document.createElement('textarea');x.id=id;x.rows=3;x.placeholder=ph;l.appendChild(x);a.closest('label')?.after(l)}
function full(addr,city){addr=(addr||'').trim();city=(city||'').trim();if(!addr)return '';if(city&&addr.toLowerCase().indexOf(city.toLowerCase())<0)return addr+', '+city;return addr}
function setv(id,v){const e=by(id);if(e)e.value=v??''}
function fields(){input('pickup','pickupAddress','Full pickup address','text','Street address only');input('delivery','deliveryAddress','Full delivery address','text','Street address only');input('deliveryAddress','loadMiles','Miles','number','Loaded miles');area('loadMiles','extraStops','Multiple stops / extra stops','Stop 1 Pickup - full address - appt\nStop 2 Delivery - full address - appt');cancelBtn()}
function row(){const pu=by('pickup')?.value||'',de=by('delivery')?.value||'';return {carrier:by('loadCarrier').value||'',broker:by('loadBroker').value||'',pickup:pu,delivery:de,pickup_address:full(by('pickupAddress')?.value,pu),delivery_address:full(by('deliveryAddress')?.value,de),miles:Number(by('loadMiles')?.value||0),additional_stops:by('extraStops')?.value||'',pickup_date:by('pickupDate').value||null,delivery_date:by('deliveryDate').value||null,pickup_time:by('pickupTime')?.value||'',delivery_time:by('deliveryTime')?.value||'',driver_name:by('driverName')?.value||'',driver_phone:by('driverPhone')?.value||'',truck_number:by('truckNumber')?.value||'',trailer_number:by('trailerNumber')?.value||'',equipment:by('equipment').value||'',status:by('loadStatus').value||'Booked',rate:Number(by('rate').value||0),commission_pct:Number(by('commissionPct').value||8),load_number:by('loadNumber').value||'',notes:by('loadNotes').value||''}}
function clear(){['pickup','delivery','pickupAddress','deliveryAddress','loadMiles','extraStops','pickupDate','deliveryDate','pickupTime','deliveryTime','driverName','driverPhone','truckNumber','trailerNumber','rate','loadNumber','loadNotes'].forEach(id=>{const e=by(id);if(e)e.value=''});editId=null;const b=by('addLoad');if(b)b.textContent='Save load';const c=by('cancelEditLoad');if(c)c.style.display='none'}
async function save(){const u=(await sb.auth.getSession()).data.session?.user;if(!u)return alert('Login again first.');const r=row();let x;if(editId){x=await sb.from('loads').update(r).eq('id',editId)}else{x=await sb.from('loads').insert({...r,user_id:u.id})}if(x.error)return alert('Save error: '+x.error.message);clear();if(typeof loadCloud==='function')await loadCloud()}
function hook(){const b=by('addLoad');if(b&&!b.dataset.phase2){b.dataset.phase2='1';b.onclick=save}}
function cancelBtn(){const b=by('addLoad');if(!b||by('cancelEditLoad'))return;const c=document.createElement('button');c.id='cancelEditLoad';c.className='small-btn';c.textContent='Cancel edit';c.style.display='none';c.onclick=clear;b.after(c)}
async function edit(i){const l=loads()[i];if(!l||!l.id)return alert('Sync first.');const r=await sb.from('loads').select('*').eq('id',l.id).single();if(r.error)return alert(r.error.message);const x=r.data;editId=x.id;fields();setv('loadCarrier',x.carrier);setv('loadBroker',x.broker);setv('pickup',x.pickup);setv('delivery',x.delivery);setv('pickupAddress',x.pickup_address);setv('deliveryAddress',x.delivery_address);setv('loadMiles',x.miles);setv('extraStops',x.additional_stops);setv('pickupDate',x.pickup_date);setv('deliveryDate',x.delivery_date);setv('pickupTime',x.pickup_time);setv('deliveryTime',x.delivery_time);setv('driverName',x.driver_name);setv('driverPhone',x.driver_phone);setv('truckNumber',x.truck_number);setv('trailerNumber',x.trailer_number);setv('equipment',x.equipment);setv('loadStatus',x.status);setv('rate',x.rate);setv('commissionPct',x.commission_pct);setv('loadNumber',x.load_number);setv('loadNotes',x.notes);const b=by('addLoad');if(b)b.textContent='Update load';const c=by('cancelEditLoad');if(c)c.style.display='inline-block';by('loads')?.scrollIntoView({behavior:'smooth',block:'start'})}
async function show(){const a=loads(),ids=a.map(x=>x.id).filter(Boolean);if(!ids.length)return;const r=await sb.from('loads').select('id,miles,pickup_address,delivery_address,additional_stops').in('id',ids);if(r.error||!r.data)return;const m=Object.fromEntries(r.data.map(x=>[x.id,x]));document.querySelectorAll('#loadsList .list-card').forEach((card,i)=>{const l=a[i];if(!l)return;let acts=card.querySelector('.card-actions');if(!acts){acts=document.createElement('div');acts.className='card-actions';card.appendChild(acts)}if(!card.querySelector('.edit-load-btn')){const e=document.createElement('button');e.className='small-btn edit-load-btn';e.textContent='Edit';e.onclick=()=>edit(i);acts.appendChild(e)}const x=m[l.id]||{};let p=card.querySelector('.phase2-line');if(!p){p=document.createElement('p');p.className='muted phase2-line';card.appendChild(p)}p.textContent='Miles: '+(x.miles||'-')+' | PU address: '+(x.pickup_address||'-')+' | DEL address: '+(x.delivery_address||'-')})}
setInterval(()=>{fields();hook();show()},1200);
})();