const CACHE_NAME="zap-dispatch-tms-v89";
const FILES=["index.html","styles.css?v=guided-tour-1","app.js?v=ratecon-quick-4","onboarding-tour.js?v=guided-tour-1","carrier-operations.js?v=admin-dual-mode-1","driver-picker.js?v=2","zap-upgrades.js?v=4500","ai-ratecon-safe.js?v=6","card-edit.js?v=commission-lock-1","admin-users.js?v=4","paywall.js?v=1","manage-subscription.js?v=1","pw-login.js?v=carrier-accounts-1","update-notice.js?v=2","eld-integrations.js?v=hos-reset-labels-1","eld-location.js?v=map-responsive-1","refresh.js?v=map-controls-1","config.js","manifest.json","zap-icon.svg","zap-logo-dark.png","zap-logo-light.png","apple-touch-icon.png","icon-192.png","icon-512.png","loadlink.js?v=zap-logo-1","vendor/supabase-js-2.110.2.js"];
/* Security headers, kept in sync with /_headers. The SW rewrites index.html into a fresh
   Response that would otherwise drop the edge headers, so we re-add them here for the shell. */
const SEC_HEADERS={"content-type":"text/html;charset=UTF-8","X-Frame-Options":"DENY","X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin","Content-Security-Policy":"default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https://unpkg.com https://tile.openstreetmap.org https://*.tile.openstreetmap.org; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; frame-ancestors 'none'; base-uri 'self'; object-src 'none'; form-action 'self'"};
const STYLE='<style>.zap-logo-login{display:block;width:min(280px,80vw);height:auto;margin:0 auto 16px}.zap-logo-head{display:block;width:220px;max-width:62vw;height:auto;margin:0 0 12px}@media(max-width:640px){.zap-logo-login{width:min(245px,82vw)}.zap-logo-head{width:185px}}.light .zap-logo-login,.light .zap-logo-head{content:url("zap-logo-light.png")}</style>';
self.addEventListener("install",e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(FILES)))});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))));self.clients.claim()});
/* Only the app shell (/ or /index.html) is intercepted for navigations. Other pages
   (portal.html, invite.html, ...) must be left to the browser: Cloudflare Pages serves
   them via a 308 clean-URL redirect, and a navigation fetch() inside the SW returns an
   opaqueredirect whose body is empty — rewriting that served a blank white page. */
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const url=new URL(e.request.url);if(url.origin!==self.location.origin)return;const path=url.pathname;if(e.request.mode==="navigate"&&path!=="/"&&!path.endsWith("/index.html"))return;e.respondWith(fetch(e.request).then(async r=>{let out=r;if(e.request.mode==="navigate"||e.request.url.endsWith("index.html")){let html=await r.clone().text();html=html.replace("<head>","<head><link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\"><link rel=\"icon\" href=\"zap-icon.svg\">"+STYLE);html=html.replace('<div class="auth-card">','<div class="auth-card"><img class="zap-logo-login" src="zap-logo-dark.png" alt="Zap Dispatch">');html=html.replace('<header class="topbar">\n    <div>','<header class="topbar">\n    <div><img class="zap-logo-head" src="zap-logo-dark.png" alt="Zap Dispatch">');html=html.replaceAll("Mini TMS Login","Zap Dispatch TMS Login").replaceAll("Mini TMS","Zap Dispatch TMS");out=new Response(html,{headers:SEC_HEADERS})}const copy=out.clone();caches.open(CACHE_NAME).then(c=>c.put(e.request,copy));return out}).catch(()=>caches.match(e.request)))})
